//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessage", ReplyAction="http://tempuri.org/IHelloService/GetMessageResponse")]
        string GetMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessage", ReplyAction="http://tempuri.org/IHelloService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetSpawnFromProcessFactory", ReplyAction="http://tempuri.org/IHelloService/GetSpawnFromProcessFactoryResponse")]
        string GetSpawnFromProcessFactory(string computername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetSpawnFromProcessFactory", ReplyAction="http://tempuri.org/IHelloService/GetSpawnFromProcessFactoryResponse")]
        System.Threading.Tasks.Task<string> GetSpawnFromProcessFactoryAsync(string computername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/NewServerProcess", ReplyAction="http://tempuri.org/IHelloService/NewServerProcessResponse")]
        string NewServerProcess(string computername, string program, string arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/NewServerProcess", ReplyAction="http://tempuri.org/IHelloService/NewServerProcessResponse")]
        System.Threading.Tasks.Task<string> NewServerProcessAsync(string computername, string program, string arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetOptions", ReplyAction="http://tempuri.org/IHelloService/GetOptionsResponse")]
        string[] GetOptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetOptions", ReplyAction="http://tempuri.org/IHelloService/GetOptionsResponse")]
        System.Threading.Tasks.Task<string[]> GetOptionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : Client.ServiceReference.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference.IHelloService>, Client.ServiceReference.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string name) {
            return base.Channel.GetMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string name) {
            return base.Channel.GetMessageAsync(name);
        }
        
        public string GetSpawnFromProcessFactory(string computername) {
            return base.Channel.GetSpawnFromProcessFactory(computername);
        }
        
        public System.Threading.Tasks.Task<string> GetSpawnFromProcessFactoryAsync(string computername) {
            return base.Channel.GetSpawnFromProcessFactoryAsync(computername);
        }
        
        public string NewServerProcess(string computername, string program, string arguments) {
            return base.Channel.NewServerProcess(computername, program, arguments);
        }
        
        public System.Threading.Tasks.Task<string> NewServerProcessAsync(string computername, string program, string arguments) {
            return base.Channel.NewServerProcessAsync(computername, program, arguments);
        }
        
        public string[] GetOptions() {
            return base.Channel.GetOptions();
        }
        
        public System.Threading.Tasks.Task<string[]> GetOptionsAsync() {
            return base.Channel.GetOptionsAsync();
        }
    }
}
